### ISSUE TITLE
Still ok to use after so many years?

### ISSUE THREAD

**Issue by TheNomad11** [vabene1111/LearningCards#2]
There are not many fkashcard solutions out there. Your project seems to be abandoned. Is it still okay to use?

**Comment by vabene1111** [comment]
Honestly not sure, you should probably at least update the dependencies. Other that that it's a very basic application so you should probably be fine.

**Comment by vabene1111** [comment]
so I recently started using this application again. I can confirm everything still works and all backend dependencies have been updated. 

At some point I (or someone) have to update the frontend dependencies which probably have some security issues but there isn't much stuff actually used so probably still save enough
